# Generated by Django 4.1.2 on 2022-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Edad', models.IntegerField(default=0)),
                ('F_Nacimiento', models.DateField()),
                ('Sexo', models.CharField(max_length=25))
            ],
        ),
    ]
