# Generated by Django 4.1.2 on 2022-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappfamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_familia',
            name='Sexo',
            field=models.CharField(max_length=30),
        ),
    ]
