# Generated by Django 4.1.2 on 2022-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappfamilia', '0002_alter_datos_familia_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='camisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Talle', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Talle', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
